trigger:
  - main

#variables:
#  image: sanjaysenthilkumar/codecoverage:latest

resources:
  containers:
  - container: codecoverage
    image: $(image)

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TestWithCustomDocker
  displayName: 'Test PublishCodeCoverageResults with Custom Docker'
  container: codecoverage
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests with coverage'
    inputs:
      command: 'test'
      projects: '**/Numbers.Tests.csproj'
      arguments: '-p:CollectCoverage=true -p:CoverletOutputFormat=cobertura'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage results'
    inputs:
      summaryFileLocation: '**/coverage.cobertura.xml'
      failIfCoverageEmpty: true